/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mypos.util;

import com.mypos.cashier.model.CartItem;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author raysu
 */
public class ReceiptPreviewDialog extends javax.swing.JDialog {
    private final String receiptNo;
    private final String cashierName;
    private final List<CartItem> items;
    private final BigDecimal total;
    private final BigDecimal pay;
    private final BigDecimal change;
    private final DecimalFormat currency = new DecimalFormat("#,###");
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReceiptPreviewDialog.class.getName());

    /**
     * Creates new form NewJDialog
     * @param parent
     * @param modal
     * @param receiptNo
     * @param cashierName
     * @param items
     * @param total
     * @param pay
     * @param change
     */
    public ReceiptPreviewDialog(java.awt.Frame parent, boolean modal, 
                                String receiptNo, String cashierName, 
                                List<CartItem> items, BigDecimal total, BigDecimal pay, BigDecimal change) {
        super(parent, modal);
        initComponents();
        this.receiptNo = receiptNo;
        this.cashierName = cashierName;
        this.items = items;
        this.total = total;
        this.pay = pay;
        this.change = change;
        tampilkanStruk(receiptNo, cashierName, items, total, pay, change);
    }
private void tampilkanStruk(String receiptNo, String cashierName, List<CartItem> items, 
                                BigDecimal total, BigDecimal pay, BigDecimal change) {
        StringBuilder sb = new StringBuilder();
        String line = "------------------------------\n"; 

        sb.append("       VENDRA POS STORE       \n");
        sb.append("    Jl. Maju Mundur No. 1     \n");
        sb.append("     Telp: 0812-3456-7890     \n");
        sb.append(line);
        sb.append("No   : ").append(receiptNo).append("\n");
        sb.append("Kasir: ").append(cashierName).append("\n");
        sb.append("Tgl  : ").append(new SimpleDateFormat("dd-MM-yyyy HH:mm").format(new Date())).append("\n");
        sb.append(line);

        for (CartItem item : items) {
            String name = item.getProductName();
            if (name.length() > 20) name = name.substring(0, 20) + "..";
            
            sb.append(name).append("\n");
            
            // Format: 2 x 5.000 = 10.000
            String qtyInfo = item.getQuantity() + " x " + currency.format(item.getPrice());
            String subTotal = currency.format(item.getSubtotal());
            
            // Trik Rata Kanan Sederhana dengan String.format
            // %-18s = Rata kiri 18 huruf, %10s = Rata kanan 10 huruf
            sb.append(String.format("%-18s %10s\n", qtyInfo, subTotal));
        }

        sb.append(line);
        sb.append(String.format("TOTAL   : %18s\n", currency.format(total)));
        sb.append(String.format("BAYAR   : %18s\n", currency.format(pay)));
        sb.append(String.format("KEMBALI : %18s\n", currency.format(change)));
        sb.append(line);
        sb.append("         TERIMA KASIH         \n");
        sb.append("   BARANG YANG SUDAH DIBELI   \n");
        sb.append("     TIDAK DAPAT DITUKAR      \n");

        Receipt.setText(sb.toString()); // Masukkan ke TextArea
        Receipt.setCaretPosition(0); // Scroll ke paling atas
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Receipt = new javax.swing.JTextArea();
        CancelPrint = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Receipt.setEditable(false);
        Receipt.setColumns(20);
        Receipt.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        Receipt.setRows(5);
        Receipt.setFocusable(false);
        jScrollPane1.setViewportView(Receipt);

        CancelPrint.setText("Cancel");
        CancelPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelPrint.addActionListener(this::CancelPrintActionPerformed);

        btnPrint.setText("Print");
        btnPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPrint.addActionListener(this::btnPrintActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CancelPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(btnPrint)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPrint, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(CancelPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelPrintActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelPrintActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        StrukPrinter printer = new StrukPrinter(receiptNo, cashierName, items, total, pay, change);
        printer.printStruk();
        dispose();
    
    }//GEN-LAST:event_btnPrintActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelPrint;
    private javax.swing.JTextArea Receipt;
    private javax.swing.JButton btnPrint;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
