/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mypos.auth.view;
import com.mypos.auth.dao.UserDao;
import com.mypos.auth.model.User;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author raysu
 */
public class UserManagementPanel extends javax.swing.JPanel {
private java.util.List<com.mypos.auth.model.User> userList;
private javax.swing.table.DefaultTableModel userTableModel;
private final com.mypos.auth.dao.UserDao userDao;
    /**
     * Creates new form UserManagementPanel
     */
    public UserManagementPanel() {
        initComponents();
        this.userDao = new com.mypos.auth.dao.UserDao();
        this.userTableModel = (javax.swing.table.DefaultTableModel) jTable2.getModel();
        loadData();
    }
           private void loadData() {
             // Fetch the latest user data
             userList = userDao.getAllUsers();
             // Clear any existing rows from the table model
             userTableModel.setRowCount(0);
    
             // Loop through the list and add each user to the table
             for (User user : userList) {
                 userTableModel.addRow(new Object[]{
                     user.getId(),
                     user.getUsername(),
                     user.getRole(),
                     user.getCreatedAt(),
                     user.getUpdatedAt()
                 });
             }
         }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        SearchBar = new javax.swing.JTextField();
        BtnSearch = new javax.swing.JButton();
        Add = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        Edit = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Name", "Role", "Create At", "Update At"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setPreferredSize(new java.awt.Dimension(800, 600));
        jScrollPane2.setViewportView(jTable2);

        SearchBar.setBackground(new java.awt.Color(153, 153, 255));
        SearchBar.setForeground(new java.awt.Color(255, 255, 255));
        SearchBar.setText("Search a name");
        SearchBar.addActionListener(this::SearchBarActionPerformed);

        BtnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-search-30.png"))); // NOI18N
        BtnSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSearch.addActionListener(this::BtnSearchActionPerformed);

        Add.setBackground(new java.awt.Color(153, 153, 255));
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add");
        Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Add.addActionListener(this::AddActionPerformed);

        Delete.setBackground(new java.awt.Color(255, 51, 51));
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.addActionListener(this::DeleteActionPerformed);

        Edit.setBackground(new java.awt.Color(153, 153, 255));
        Edit.setForeground(new java.awt.Color(255, 255, 255));
        Edit.setText("Edit");
        Edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Edit.addActionListener(this::EditActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 959, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSearchActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
     int selectedRow = jTable2.getSelectedRow();
     if (selectedRow == -1) {
         javax.swing.JOptionPane.showMessageDialog(this, "Please select a user to edit.", "Warning",
      javax.swing.JOptionPane.WARNING_MESSAGE);
         return;
     }
    
     // Convert view index to model index in case of sorting
     int modelRow = jTable2.convertRowIndexToModel(selectedRow);
     int userId = (int) userTableModel.getValueAt(modelRow, 0);
   
    com.mypos.auth.model.User userToEdit = null;
    for(com.mypos.auth.model.User user : userList) {
        if(user.getId() == userId) {
            userToEdit = user;
            break;
        }
    }
   
    if (userToEdit == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Could not find user data to edit.", "Error",
      javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
   
    // Find the parent window for the dialog
    java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
   
    // Reuse AddUserDialog for editing
    com.mypos.auth.view.AddUserDialog dialog = new com.mypos.auth.view.AddUserDialog((java.awt.Frame) parentWindow, true);
   
    // TODO: You still need to add setter methods to your AddUserDialog
    // to pre-fill the data before showing it.
    // Example:
    // dialog.setUsername(userToEdit.getUsername());
    // dialog.setRole(userToEdit.getRole());
    // dialog.setFieldsForEdit(); // a method to hide/disable password field
   
    dialog.setVisible(true);
   
    dialog.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            if (dialog.isConfirmed()) {
                com.mypos.auth.model.User updatedUser = new com.mypos.auth.model.User();
                updatedUser.setId(userId);
                updatedUser.setUsername(dialog.getUsername());
                updatedUser.setRole(dialog.getRole());
                updatedUser.setPassword(dialog.getPassword()); // DAO handles if this is empty
   
                if (userDao.updateUser(updatedUser)) {
                    javax.swing.JOptionPane.showMessageDialog(UserManagementPanel.this, "User updated successfully!");
                    loadData(); // Refresh table
                } else {
                    javax.swing.JOptionPane.showMessageDialog(UserManagementPanel.this, "Failed to update user.", "Database Error",
      javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    });
    }//GEN-LAST:event_EditActionPerformed

    private void SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBarActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
     // Find the top-level window (the MainFrame) to act as the parent
     java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
    
     // Create the dialog, passing the parent window and setting it as modal
     com.mypos.auth.view.AddUserDialog dialog = new com.mypos.auth.view.AddUserDialog((java.awt.Frame) parentWindow, true);
    
     dialog.addWindowListener(new java.awt.event.WindowAdapter() {
     @Override
         public void windowClosed(java.awt.event.WindowEvent e) {
         if (dialog.isConfirmed()) {             String username = dialog.getUsername();
             String password = dialog.getPassword();
                String role = dialog.getRole();
   
                if (username.isEmpty() || password.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(UserManagementPanel.this, "Username and password cannot be empty.",
      "Validation Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }
   
                com.mypos.auth.model.User newUser = new com.mypos.auth.model.User(username, password, role);
                if (userDao.addUser(newUser)) {
                    javax.swing.JOptionPane.showMessageDialog(UserManagementPanel.this, "User added successfully!");
                    loadData(); // Refresh table
                } else {
                    javax.swing.JOptionPane.showMessageDialog(UserManagementPanel.this, "Failed to add user.", "Database Error",
      javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    });
   
    dialog.setVisible(true); // Show the dialog
    
   
    }//GEN-LAST:event_AddActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
         int selectedRow = jTable2.getSelectedRow();
     if (selectedRow == -1) {
         javax.swing.JOptionPane.showMessageDialog(this, "Please select a user to delete.", "Warning",
      javax.swing.JOptionPane.WARNING_MESSAGE);
         return;
     }
    
     int userId = (int) userTableModel.getValueAt(selectedRow, 0);
     String username = (String) userTableModel.getValueAt(selectedRow, 1);
    
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to delete user '" + username + "'?",
      "Confirm Deletion", javax.swing.JOptionPane.YES_NO_OPTION);
   
    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        if (userDao.deleteUser(userId)) {
            javax.swing.JOptionPane.showMessageDialog(this, "User deleted successfully!");
            loadData(); // Refresh table
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Failed to delete user.", "Database Error",
      javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_DeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton BtnSearch;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField SearchBar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
