package com.mypos.cashier.view;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author HP
 */
public class CheckoutPayment extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CheckoutPayment.class.getName());
    private final BigDecimal totalAmount;
    private boolean isPaymentSuccess = false;
    private final NumberFormat currencyFormatter;
    /**
     * Creates new form TryDialog
     * @param parent
     * @param modal
     * @param total
     */
    public CheckoutPayment(java.awt.Frame parent, boolean modal, BigDecimal total) {
        super(parent, modal);
        
        // 1. Simpan total tagihan
        this.totalAmount = total;
        
        // 2. Siapkan formatter Rupiah
        this.currencyFormatter = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
        
        initComponents(); // Inisialisasi komponen desain
        
        // 3. Tampilkan Total Tagihan di field 'Bill'
        // (Menggunakan nama variabel 'Bill' sesuai desainmu)
        Bill.setText(currencyFormatter.format(this.totalAmount));
        
        // 4. Reset field input
        PaymentField.setText("");
        ChangeField.setText("");
        
        // 5. Tambah listener untuk hitung kembalian otomatis
        PaymentField.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                calculateChange(); // Panggil fungsi hitung
            }
        });

        setLocationRelativeTo(parent);
    }

    public boolean isPaymentSuccess() {
        return this.isPaymentSuccess;
    }

    /**
     * Dynamically calculates and displays the change.
     */
    private void calculateChange() {
        try {
            // Ambil teks dari PaymentField
            String paymentText = PaymentField.getText();
            
            if (paymentText.isEmpty()) {
                ChangeField.setText("");
                return;
            }

            // Hitung: Uang Masuk - Tagihan
            BigDecimal paymentAmount = new BigDecimal(paymentText);
            BigDecimal changeAmount = paymentAmount.subtract(totalAmount);

            // Tampilkan di ChangeField
            ChangeField.setText(currencyFormatter.format(changeAmount));

        } catch (NumberFormatException e) {
            ChangeField.setText("Invalid input");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        Payment = new javax.swing.JLabel();
        Change = new javax.swing.JLabel();
        Amount = new javax.swing.JLabel();
        PaymentField = new javax.swing.JTextField();
        CancelPayment = new javax.swing.JButton();
        SubmitPayment = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Bill = new javax.swing.JTextField();
        ChangeField = new javax.swing.JTextField();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PAYMENT");
        setResizable(false);

        Payment.setText("Payment        :");

        Change.setText("Change           :");

        Amount.setText("Amount         :");

        PaymentField.addActionListener(this::PaymentFieldActionPerformed);

        CancelPayment.setBackground(new java.awt.Color(255, 255, 204));
        CancelPayment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CancelPayment.setForeground(new java.awt.Color(102, 102, 0));
        CancelPayment.setText("Cancel");
        CancelPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CancelPayment.addActionListener(this::CancelPaymentActionPerformed);

        SubmitPayment.setBackground(new java.awt.Color(204, 204, 255));
        SubmitPayment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SubmitPayment.setForeground(new java.awt.Color(102, 102, 255));
        SubmitPayment.setText("Submit");
        SubmitPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SubmitPayment.addActionListener(this::SubmitPaymentActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setText("PAYMENT SALE");

        Bill.setEditable(false);
        Bill.setFocusable(false);
        Bill.addActionListener(this::BillActionPerformed);

        ChangeField.setEditable(false);
        ChangeField.setFocusable(false);
        ChangeField.addActionListener(this::ChangeFieldActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(Change)
                                .addGap(18, 18, 18)
                                .addComponent(ChangeField, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Payment)
                                    .addComponent(Amount))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(PaymentField)
                                        .addComponent(Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CancelPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151)
                        .addComponent(SubmitPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Amount, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaymentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Payment))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Change)
                    .addComponent(ChangeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SubmitPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelPaymentActionPerformed
        this.isPaymentSuccess = false;
        this.dispose();
    }//GEN-LAST:event_CancelPaymentActionPerformed

    private void PaymentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentFieldActionPerformed

    private void BillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BillActionPerformed

    private void ChangeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ChangeFieldActionPerformed

    private void SubmitPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitPaymentActionPerformed
        try {
            String paymentText = PaymentField.getText();
            if (paymentText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Harap masukkan jumlah uang!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }

            BigDecimal paymentAmount = new BigDecimal(paymentText);

            if (paymentAmount.compareTo(totalAmount) < 0) {
                JOptionPane.showMessageDialog(this, "Uang pembayaran kurang!", "Gagal", JOptionPane.WARNING_MESSAGE);
                return;
            }

            this.isPaymentSuccess = true;
            this.dispose(); // Tutup dialog

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Input uang tidak valid (Hanya Angka)!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_SubmitPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            // UBAH BARIS INI: Tambahkan , new BigDecimal("0") di akhir kurung
            CheckoutPayment dialog = new CheckoutPayment(new javax.swing.JFrame(), true, new BigDecimal("0"));
            
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Amount;
    private javax.swing.JTextField Bill;
    private javax.swing.JButton CancelPayment;
    private javax.swing.JLabel Change;
    private javax.swing.JTextField ChangeField;
    private javax.swing.JLabel Payment;
    private javax.swing.JTextField PaymentField;
    private javax.swing.JButton SubmitPayment;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    // Tambahkan di CheckoutPayment.java
    public java.math.BigDecimal getPaidAmount() {
    try {
        return new java.math.BigDecimal(PaymentField.getText());
    } catch (Exception e) {
        return java.math.BigDecimal.ZERO;
    }
}

    public java.math.BigDecimal getChangeAmount() {
    // Hitung ulang atau ambil dari textfield
    try {
        java.math.BigDecimal paid = getPaidAmount();
        return paid.subtract(this.totalAmount);
    } catch (Exception e) {
        return java.math.BigDecimal.ZERO;
    }
}

}
