package com.mypos.cashier.view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author HP
 */
public class ReceiptSale extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReceiptSale.class.getName());

    /**
     * Creates new form TryDialog
     * @param parent
     * @param modal
     */
    public ReceiptSale(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        SaveReceiptNote = new javax.swing.JButton();
        PrintReceiptNote = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TotalPriceLabel = new javax.swing.JLabel();
        TotalAmountLabel = new javax.swing.JLabel();
        ReturnTotalLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        DateSaleLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        NameStoreLabel = new javax.swing.JLabel();
        AddressStoreLabel = new javax.swing.JLabel();
        NoTelpLabel = new javax.swing.JLabel();
        IdCashierLabel = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        IdTransactionLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RECEIPT");
        setResizable(false);

        jLabel2.setText("Total               :");

        jLabel3.setText("Return             :");

        jLabel4.setText("Amount          :");

        SaveReceiptNote.setBackground(new java.awt.Color(255, 255, 204));
        SaveReceiptNote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SaveReceiptNote.setForeground(new java.awt.Color(102, 102, 0));
        SaveReceiptNote.setText("SAVE");
        SaveReceiptNote.addActionListener(this::SaveReceiptNoteActionPerformed);

        PrintReceiptNote.setBackground(new java.awt.Color(204, 204, 255));
        PrintReceiptNote.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PrintReceiptNote.setForeground(new java.awt.Color(102, 102, 255));
        PrintReceiptNote.setText("PRINT");
        PrintReceiptNote.addActionListener(this::PrintReceiptNoteActionPerformed);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel6.setText("RECEIPT NOTES ");

        TotalPriceLabel.setText("1000000,00");

        TotalAmountLabel.setText("1200000,00");

        ReturnTotalLabel.setText("200000,00");

        jLabel9.setText("Datesale         :");

        DateSaleLabel.setText("08/09/2025");

        jLabel11.setText("ID Cashier      :");

        jLabel12.setText("No Telp.         :");

        jLabel13.setText("Store             :");

        jLabel14.setText("Address         :");

        NameStoreLabel.setText("Vendra POS ");

        AddressStoreLabel.setText("Jl. Maju Mundur");

        NoTelpLabel.setText("08567439265");

        IdCashierLabel.setText("001");

        jLabel18.setText("ID Trx            :");

        IdTransactionLabel.setText("001");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SaveReceiptNote, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(IdTransactionLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(DateSaleLabel)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(NoTelpLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(AddressStoreLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(18, 18, 18)
                                        .addComponent(NameStoreLabel)
                                        .addGap(94, 94, 94)
                                        .addComponent(jLabel11)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IdCashierLabel)
                                    .addComponent(TotalPriceLabel)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ReturnTotalLabel)
                                        .addComponent(TotalAmountLabel))))
                            .addComponent(PrintReceiptNote, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 34, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(IdTransactionLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(NameStoreLabel)
                    .addComponent(jLabel11)
                    .addComponent(IdCashierLabel))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(AddressStoreLabel)
                    .addComponent(jLabel2)
                    .addComponent(TotalPriceLabel))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(NoTelpLabel)
                    .addComponent(jLabel4)
                    .addComponent(TotalAmountLabel))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(DateSaleLabel)
                    .addComponent(jLabel3)
                    .addComponent(ReturnTotalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveReceiptNote, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PrintReceiptNote, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveReceiptNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveReceiptNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveReceiptNoteActionPerformed

    private void PrintReceiptNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintReceiptNoteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintReceiptNoteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ReceiptSale dialog = new ReceiptSale(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressStoreLabel;
    private javax.swing.JLabel DateSaleLabel;
    private javax.swing.JLabel IdCashierLabel;
    private javax.swing.JLabel IdTransactionLabel;
    private javax.swing.JLabel NameStoreLabel;
    private javax.swing.JLabel NoTelpLabel;
    private javax.swing.JButton PrintReceiptNote;
    private javax.swing.JLabel ReturnTotalLabel;
    private javax.swing.JButton SaveReceiptNote;
    private javax.swing.JLabel TotalAmountLabel;
    private javax.swing.JLabel TotalPriceLabel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
