/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mypos.sales.view;

import com.mypos.sales.model.Sale;
import com.mypos.sales.model.SalesSummary;
import com.mypos.sales.service.SalesService;
import com.mypos.store.dao.StoreDao;
import com.mypos.store.dao.StoreDaoImpl;
import com.mypos.store.model.Store;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.font.PDType1Font;

import javax.swing.*;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.awt.Component;
import java.io.File;
import java.math.BigDecimal;
import java.text.NumberFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Locale;
/**
 *
 * @author USER
 */

public class SalesPanel extends javax.swing.JPanel {

    /**
     * Creates new form SalesPanel
     */
    
    private final SalesService salesService = new SalesService();
    private final DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private final NumberFormat currencyFmt = NumberFormat.getCurrencyInstance(new Locale("id","ID"));
    
    
    public SalesPanel() {
        initComponents();
        IntervalSales.setSelectedItem("Today");
        setupTableRenderers();
        loadSalesData();
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentShown(java.awt.event.ComponentEvent e) {
                // Saat panel ini muncul, refresh data otomatis
                loadSalesData();
                System.out.println("SalesPanel Refreshed Automatically!");
            }
        });
    }

    private void setupTableRenderers() {
        CurrencyRenderer renderer = new CurrencyRenderer();
        // Asumsi urutan kolom: [0:ID], [1:User], [2:Receipt], [3:Total], [4:Paid], [5:Change], [6:Date]
        if (SalesTable.getColumnCount() >= 6) {
            SalesTable.getColumnModel().getColumn(3).setCellRenderer(renderer); // Total
            SalesTable.getColumnModel().getColumn(4).setCellRenderer(renderer); // Paid
            SalesTable.getColumnModel().getColumn(5).setCellRenderer(renderer); // Change
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        SalesTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        IntervalSales = new javax.swing.JComboBox<>();
        ExportSales = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1030, 670));

        jScrollPane2.setPreferredSize(new java.awt.Dimension(800, 700));

        SalesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Transaction", "UserName", "Receipt Number", "Total Amount", "Amount Paid", "Change Amount", "Sale Datetime"
            }
        ));
        SalesTable.setPreferredSize(new java.awt.Dimension(800, 700));
        jScrollPane2.setViewportView(SalesTable);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("TRANSACTION");

        IntervalSales.setBackground(new java.awt.Color(153, 153, 255));
        IntervalSales.setForeground(new java.awt.Color(255, 255, 255));
        IntervalSales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Today", "Weekly", "Monthly", "All Time" }));
        IntervalSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IntervalSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntervalSalesActionPerformed(evt);
            }
        });

        ExportSales.setBackground(new java.awt.Color(153, 153, 255));
        ExportSales.setForeground(new java.awt.Color(255, 255, 255));
        ExportSales.setText("EXPORT PDF");
        ExportSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExportSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExportSalesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ExportSales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IntervalSales, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IntervalSales, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExportSales, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IntervalSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntervalSalesActionPerformed
        loadSalesData();
    }//GEN-LAST:event_IntervalSalesActionPerformed

    private void ExportSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExportSalesActionPerformed
        new Thread(() -> {
            try {
                String interval = (String) IntervalSales.getSelectedItem();
                List<Sale> list = salesService.getSalesByInterval(interval);
                exportSalesListToPdf(list, interval);
                SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, "Export PDF selesai. Cek folder Downloads.", "Sukses", JOptionPane.INFORMATION_MESSAGE));
            } catch (Exception e) {
                e.printStackTrace();
                SwingUtilities.invokeLater(() -> JOptionPane.showMessageDialog(this, "Gagal export PDF:\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE));
            }
        }).start();
    }//GEN-LAST:event_ExportSalesActionPerformed
    
    private void loadSalesData() {
        SwingUtilities.invokeLater(() -> {
            DefaultTableModel model = (DefaultTableModel) SalesTable.getModel();
            model.setRowCount(0); // Bersihkan baris lama
            
            String interval = (String) IntervalSales.getSelectedItem();

            try {
                // Ambil data lewat Service (yang memanggil DAO)
                List<Sale> list = salesService.getSalesByInterval(interval);

                for (Sale s : list) {
                    Object[] row = new Object[] {
                        s.getId(),
                        
                        // TAMPILKAN NAMA KASIR
                        s.getCashierName(), 
                        
                        s.getReceiptNumber(),
                        
                        // Data Uang (BigDecimal Asli) -> Biar Renderer yang format
                        s.getTotalAmount(), 
                        s.getAmountPaid(), 
                        s.getChangeAmount(),
                        
                        s.getSaleDate() == null ? "" : s.getSaleDate().format(dtf)
                    };
                    model.addRow(row);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "Gagal memuat data sales:\n" + ex.getMessage(), "DB Error", JOptionPane.ERROR_MESSAGE);
            }
        });
    }
    
 private void exportSalesListToPdf(List<Sale> list, String interval) throws Exception {
    if (list == null || list.isEmpty()) throw new Exception("Tidak ada data untuk diexport.");

    StoreDao storeDao = new StoreDaoImpl();
    Store store = storeDao.getStoreInfo();
    SalesSummary summary = salesService.getSummaryByInterval(interval);

    PDDocument doc = new PDDocument();
    PDPage page = new PDPage();
    doc.addPage(page);

    // Page metrics
    final float margin = 50f;
    final float pageWidth = page.getMediaBox().getWidth();
    final float pageHeight = page.getMediaBox().getHeight();
    final float usableWidth = pageWidth - margin * 2f;

    // layout: kolom berdasarkan persentase dari usableWidth
    // Atur persentase sesuai kebutuhan agar tidak terpotong
    final double pctNo = 0.05;      // 5%
    final double pctUser = 0.08;    // 8%
    final double pctReceipt = 0.18; // 22%
    final double pctTotal = 0.19;   // 16%
    final double pctPaid = 0.15;    // 15%
    final double pctChange = 0.12;  // 15%
    final double pctDate = 0.17;    // 19% (sisa)

    final float colNoW = (float)(usableWidth * pctNo);
    final float colUserW = (float)(usableWidth * pctUser);
    final float colReceiptW = (float)(usableWidth * pctReceipt);
    final float colTotalW = (float)(usableWidth * pctTotal);
    final float colPaidW = (float)(usableWidth * pctPaid);
    final float colChangeW = (float)(usableWidth * pctChange);
    final float colDateW = (float)(usableWidth * pctDate);

    // compute X positions (left edges)
    final float colX0 = margin;
    final float colX1 = colX0 + colNoW + 8f;
    final float colX2 = colX1 + colUserW + 8f;
    final float colX3 = colX2 + colReceiptW + 4f; // Total starts here
    final float colX4 = colX3 + colTotalW + 6f;    // Paid
    final float colX5 = colX4 + colPaidW + 7f;     // Change
    final float colX6 = colX5 + colChangeW + 11f;   // Date (rightmost)

    // Fonts & sizes
    final float headerFontSize = 16f;
    final float subHeaderFontSize = 10f;
    final float tableHeaderFontSize = 10f;
    final float tableFontSize = 9f;
    final float footerFontSize = 10f;

    // vertical spacing
    final float rowLeading = 18f; // increased spacing between rows

    // Y start
    final float yStart = pageHeight - margin;
    float y = yStart;

    PDPageContentStream cs = new PDPageContentStream(doc, page);

    // Draw document header ONCE (first page); returns y after header
    y = drawDocumentHeader(cs, store, interval, margin, yStart, pageWidth, headerFontSize, subHeaderFontSize);

    // small gap then table header
    y -= 8f;

    // TABLE HEADER (draw once on first page)
    cs.beginText();
    cs.setFont(PDType1Font.HELVETICA_BOLD, tableHeaderFontSize);
    cs.newLineAtOffset(colX0, y);
    cs.showText("No");
    cs.endText();

    cs.beginText();
    cs.setFont(PDType1Font.HELVETICA_BOLD, tableHeaderFontSize);
    cs.newLineAtOffset(colX1, y);
    cs.showText("User");
    cs.endText();

    cs.beginText();
    cs.setFont(PDType1Font.HELVETICA_BOLD, tableHeaderFontSize);
    cs.newLineAtOffset(colX2, y);
    cs.showText("Receipt");
    cs.endText();

    // center numeric headers inside their column widths
    String hdrTotal = "         Total";
    float hdrTotalW = PDType1Font.HELVETICA_BOLD.getStringWidth(hdrTotal) / 1000 * tableHeaderFontSize;
    float startTotalX = colX3 + (colTotalW - hdrTotalW) / 2f;
    cs.beginText(); cs.setFont(PDType1Font.HELVETICA_BOLD, tableHeaderFontSize);
    cs.newLineAtOffset(startTotalX, y); cs.showText(hdrTotal); cs.endText();

    String hdrPaid = "     Paid";
    float hdrPaidW = PDType1Font.HELVETICA_BOLD.getStringWidth(hdrPaid) / 1000 * tableHeaderFontSize;
    float startPaidX = colX4 + (colPaidW - hdrPaidW) / 2f;
    cs.beginText(); cs.setFont(PDType1Font.HELVETICA_BOLD, tableHeaderFontSize);
    cs.newLineAtOffset(startPaidX, y); cs.showText(hdrPaid); cs.endText();

    String hdrChange = "   Change";
    float hdrChangeW = PDType1Font.HELVETICA_BOLD.getStringWidth(hdrChange) / 1000 * tableHeaderFontSize;
    float startChangeX = colX5 + (colChangeW - hdrChangeW) / 2f;
    cs.beginText(); cs.setFont(PDType1Font.HELVETICA_BOLD, tableHeaderFontSize);
    cs.newLineAtOffset(startChangeX, y); cs.showText(hdrChange); cs.endText();

    String hdrDate = "Sale Date";
    float hdrDateW = PDType1Font.HELVETICA_BOLD.getStringWidth(hdrDate) / 1000 * tableHeaderFontSize;
    float startDateX = colX6 + (colDateW - hdrDateW) / 2f;
    cs.beginText(); cs.setFont(PDType1Font.HELVETICA_BOLD, tableHeaderFontSize);
    cs.newLineAtOffset(startDateX, y); cs.showText(hdrDate); cs.endText();

    // move to first data row
    y -= (tableHeaderFontSize + 6f);

    // Use monospace font for table body (stable width)
    final PDType1Font tableFont = PDType1Font.COURIER;

    int no = 1;
    DateTimeFormatter dtfShort = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    int pageNumber = 1;
    for (int i = 0; i < list.size(); i++) {
        Sale s = list.get(i);

        // if running out of space -> new page (do NOT draw document header again)
        if (y < margin + 120f) {
            cs.close();
            page = new PDPage();
            doc.addPage(page);
            cs = new PDPageContentStream(doc, page);
            pageNumber++;
            // Start content a bit below top margin on subsequent pages
            y = yStart - 30f;
        }

        // No (left aligned)
        cs.beginText(); cs.setFont(tableFont, tableFontSize);
        cs.newLineAtOffset(colX0, y);
        cs.showText(String.valueOf(no++));
        cs.endText();

        // User (left aligned)
        cs.beginText(); cs.setFont(tableFont, tableFontSize);
        cs.newLineAtOffset(colX1, y);
        cs.showText(String.valueOf(s.getUserId()));
        cs.endText();

        // Receipt (left aligned, truncated)
        String receipt = s.getReceiptNumber() == null ? "" : s.getReceiptNumber();
        String receiptTrunc = truncate(receipt, 40);
        cs.beginText(); cs.setFont(tableFont, tableFontSize);
        cs.newLineAtOffset(colX2, y);
        cs.showText(receiptTrunc);
        cs.endText();

        // Numeric columns: right-aligned inside their column widths
        String totalStr = formatCurrencySimple(s.getTotalAmount());
        String paidStr = formatCurrencySimple(s.getAmountPaid());
        String changeStr = formatCurrencySimple(s.getChangeAmount());

        float totalRight = colX3 + colTotalW - 6f;   // right edge minus padding
        float paidRight  = colX4 + colPaidW - 6f;
        float changeRight= colX5 + colChangeW - 6f;

        float tw = tableFont.getStringWidth(totalStr) / 1000 * tableFontSize;
        cs.beginText(); cs.setFont(tableFont, tableFontSize);
        cs.newLineAtOffset(totalRight - tw, y);
        cs.showText(totalStr);
        cs.endText();

        float pw = tableFont.getStringWidth(paidStr) / 1000 * tableFontSize;
        cs.beginText(); cs.setFont(tableFont, tableFontSize);
        cs.newLineAtOffset(paidRight - pw, y);
        cs.showText(paidStr);
        cs.endText();

        float cw = tableFont.getStringWidth(changeStr) / 1000 * tableFontSize;
        cs.beginText(); cs.setFont(tableFont, tableFontSize);
        cs.newLineAtOffset(changeRight - cw, y);
        cs.showText(changeStr);
        cs.endText();

        // Sale date (left aligned in its column)
        String dateStr = s.getSaleDate() == null ? "" : s.getSaleDate().format(dtfShort);
        cs.beginText(); cs.setFont(tableFont, tableFontSize);
        cs.newLineAtOffset(colX6, y);
        cs.showText(dateStr);
        cs.endText();

        // decrease y by rowLeading for spacing between rows
        y -= rowLeading;
    }

    // separator before summary on last page
    y -= 4f;
    cs.moveTo(margin, y);
    cs.lineTo(pageWidth - margin, y);
    cs.stroke();
    y -= 12f;

    // FOOTER / SUMMARY on last page
    cs.beginText(); cs.setFont(PDType1Font.HELVETICA_BOLD, 12f);
    cs.newLineAtOffset(margin, y);
    cs.showText("SUMMARY");
    cs.endText();
    y -= (12f + 6f);

    cs.setFont(PDType1Font.HELVETICA, footerFontSize);
    cs.beginText(); cs.newLineAtOffset(margin, y); cs.showText("Total Transactions : " + summary.getTotalTransactions()); cs.endText(); y -= (footerFontSize + 4f);
    cs.beginText(); cs.newLineAtOffset(margin, y); cs.showText("Total Amount       : " + formatCurrency(summary.getTotalAmount())); cs.endText(); y -= (footerFontSize + 4f);
    cs.beginText(); cs.newLineAtOffset(margin, y); cs.showText("Total Paid         : " + formatCurrency(summary.getTotalPaid())); cs.endText(); y -= (footerFontSize + 4f);
    cs.beginText(); cs.newLineAtOffset(margin, y); cs.showText("Total Change       : " + formatCurrency(summary.getTotalChange())); cs.endText(); y -= (footerFontSize + 4f);

    // page number bottom-right
    String pageNumText = "Page " + pageNumber;
    float pntw = PDType1Font.HELVETICA.getStringWidth(pageNumText) / 1000 * footerFontSize;
    cs.beginText(); cs.setFont(PDType1Font.HELVETICA, footerFontSize);
    cs.newLineAtOffset(pageWidth - margin - pntw, margin / 2);
    cs.showText(pageNumText);
    cs.endText();

    cs.close();

    // Save file...
    File downloads = getDownloadsFolder();
    if (!downloads.exists()) downloads.mkdirs();
    String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
    String fileName = "Laporan_Penjualan_" + timestamp.replace(":", "-") + ".pdf";
    File out = new File(downloads, fileName);
    doc.save(out);
    doc.close();
    System.out.println("Saved PDF to: " + out.getAbsolutePath());
}


    
    private float drawDocumentHeader(PDPageContentStream cs, Store store, String interval,
                                 float margin, float yStart, float pageWidth,
                                 float headerFontSize, float subHeaderFontSize) throws Exception {
    float y = yStart;

    // Store name (left)
    cs.beginText();
    cs.setFont(PDType1Font.HELVETICA_BOLD, headerFontSize);
    cs.newLineAtOffset(margin, y);
    cs.showText(store != null && store.getName() != null ? store.getName() : "STORE NAME");
    cs.endText();
    y -= headerFontSize + 4;

    // Store address & phone (left)
    cs.beginText();
    cs.setFont(PDType1Font.HELVETICA, subHeaderFontSize);
    cs.newLineAtOffset(margin, y);
    String addr = (store != null && store.getAddress() != null) ? store.getAddress() : "STORE ADDRESS";
    cs.showText(addr);
    cs.endText();
    y -= subHeaderFontSize + 2;

    cs.beginText();
    cs.setFont(PDType1Font.HELVETICA, subHeaderFontSize);
    cs.newLineAtOffset(margin, y);
    cs.showText("Telp: " + ((store != null && store.getPhone() != null) ? store.getPhone() : "-"));
    cs.endText();

    // Export timestamp & periode (right) -> align right on the top line
    String timestamp = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
    String rightLine = "Periode: " + interval + "    Export: " + timestamp;
    float textWidth = PDType1Font.HELVETICA.getStringWidth(rightLine) / 1000 * subHeaderFontSize;
    cs.beginText();
    cs.setFont(PDType1Font.HELVETICA, subHeaderFontSize);
    cs.newLineAtOffset(pageWidth - margin - textWidth, y + (headerFontSize + 4) - subHeaderFontSize); // align with top
    cs.showText(rightLine);
    cs.endText();

    // draw separator line under header
    y -= (subHeaderFontSize + 10f);
    float sepY = y + 6f;
    cs.moveTo(margin, sepY);
    cs.lineTo(pageWidth - margin, sepY);
    cs.stroke();

    return y;
}

    
    // --- Helper Methods ---

    private String truncate(String s, int max) {
        if (s == null) return "";
        return s.length() <= max ? s : s.substring(0, max-3) + "...";
    }

    private File getDownloadsFolder() {
        String userHome = System.getProperty("user.home");
        File downloads = new File(userHome, "Downloads");
        if (downloads.exists() && downloads.isDirectory()) return downloads;
        return new File(userHome);
    }

    private String formatCurrency(BigDecimal value) {
        if (value == null) return currencyFmt.format(0);
        return currencyFmt.format(value);
    }

    private String formatCurrencySimple(BigDecimal value) {
        if (value == null) return "0";
        return value.toPlainString();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExportSales;
    private javax.swing.JComboBox<String> IntervalSales;
    private javax.swing.JTable SalesTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

static class CurrencyRenderer extends DefaultTableCellRenderer {
        private static final NumberFormat FORMATTER = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
            
            if (value instanceof BigDecimal) {
                setText(FORMATTER.format(value));
                setHorizontalAlignment(SwingConstants.RIGHT);
            } else {
                setText(value == null ? "" : value.toString());
                setHorizontalAlignment(SwingConstants.LEFT);
            }
            return this;
        }
    }
}
